# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
"""Client and server classes corresponding to protobuf-defined services."""
import grpc

import check_type_spec_pb2 as check__type__spec__pb2


class CheckTypeSpecStub(object):
    """Missing associated documentation comment in .proto file."""

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.UploadCheckResult = channel.unary_unary(
                '/checktypespec.CheckTypeSpec/UploadCheckResult',
                request_serializer=check__type__spec__pb2.CheckRequest.SerializeToString,
                response_deserializer=check__type__spec__pb2.CheckReply.FromString,
                )


class CheckTypeSpecServicer(object):
    """Missing associated documentation comment in .proto file."""

    def UploadCheckResult(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')


def add_CheckTypeSpecServicer_to_server(servicer, server):
    rpc_method_handlers = {
            'UploadCheckResult': grpc.unary_unary_rpc_method_handler(
                    servicer.UploadCheckResult,
                    request_deserializer=check__type__spec__pb2.CheckRequest.FromString,
                    response_serializer=check__type__spec__pb2.CheckReply.SerializeToString,
            ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
            'checktypespec.CheckTypeSpec', rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler,))


 # This class is part of an EXPERIMENTAL API.
class CheckTypeSpec(object):
    """Missing associated documentation comment in .proto file."""

    @staticmethod
    def UploadCheckResult(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(request, target, '/checktypespec.CheckTypeSpec/UploadCheckResult',
            check__type__spec__pb2.CheckRequest.SerializeToString,
            check__type__spec__pb2.CheckReply.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)
