# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: protos/helloworld.proto
"""Generated protocol buffer code."""
from google.protobuf.internal import builder as _builder
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x17protos/helloworld.proto\x12\nhelloworld\"S\n\x0cHelloRequest\x12\x0f\n\x07str_val\x18\x01 \x01(\t\x12\x1d\n\x10optional_str_val\x18\x02 \x01(\tH\x00\x88\x01\x01\x42\x13\n\x11_optional_str_val\"\x1d\n\nHelloReply\x12\x0f\n\x07message\x18\x01 \x01(\t2I\n\x07Greeter\x12>\n\x08SayHello\x12\x18.helloworld.HelloRequest\x1a\x16.helloworld.HelloReply\"\x00\x62\x06proto3')

_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, globals())
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'protos.helloworld_pb2', globals())
if _descriptor._USE_C_DESCRIPTORS == False:

  DESCRIPTOR._options = None
  _HELLOREQUEST._serialized_start=39
  _HELLOREQUEST._serialized_end=122
  _HELLOREPLY._serialized_start=124
  _HELLOREPLY._serialized_end=153
  _GREETER._serialized_start=155
  _GREETER._serialized_end=228
# @@protoc_insertion_point(module_scope)
